# This action file handles the deployment of CINet project.
# - Builds docker image for CINet.
# - Pushes image to hub.ncsa.illinois.edu with its respective tag.
# - Sets up SSH to VM and pulls the new image.
name: CINet Build & Deploy

# Controls when the action will run. Triggers the workflow on push
# and pull request events for main and develop branches only.
on:
  push:
    branches:
      - main
#      - develop
#  pull_request:
#    branches:
#      - main
#      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        name:
          - CINet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - # Generates the tags and gets the version number from package.json files
        # For develop branch, image is tagged with `develop` and the git sha of the latest commit
        # For main branch, image is tagged with `latest` and the version number in their package.json
        name: Gather Information
        id: info
        env:
          PROJECT_NAME: cinet
          HUB_REPO: hub.ncsa.illinois.edu/geostreams
          GITHUB_SHA: ${{ github.sha }}
        run: |
          TARGET_BRANCH=${GITHUB_REF#refs/*/}
          echo ${TARGET_BRANCH}
          VERSION="$(grep version package.json | awk -F \" '{print $4}')"
          echo -n > .env
          TAGS="${HUB_REPO}/${PROJECT_NAME}:latest,${HUB_REPO}/${PROJECT_NAME}:${VERSION}"
          PUSH_IMAGE=true
          # Fix and enable the following after setting up a dev server.
          # The issue is TARGET_BRANCH is not set correctly for PRs
          # if [ "$TARGET_BRANCH" == "main" ]; then
          #   TAGS="${HUB_REPO}/${PROJECT_NAME}:latest,${HUB_REPO}/${PROJECT_NAME}:${VERSION}"
          #   PUSH_IMAGE=true
          # elif [ "$TARGET_BRANCH" == "develop" ]; then
          #   TAGS="${HUB_REPO}/${PROJECT_NAME}:develop,${HUB_REPO}/${PROJECT_NAME}:sha-${GITHUB_SHA::8}"
          #   PUSH_IMAGE=true
          # else
          #   PUSH_IMAGE=false
          # fi
          echo "SSH_HOST=${{ matrix['host'] }}" >> $GITHUB_ENV
          echo "::set-output name=push_image::${PUSH_IMAGE}"
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=tags::${TAGS}"
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Test Vars
        run: |
          echo "HOST: " ${{ env.SSH_HOST }} ${{ steps.info.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Hub
        uses: docker/login-action@v1
        with:
          registry: hub.ncsa.illinois.edu
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - # Docker build and push action.
        # Attaches tags generated above and labels to the image before pushing
        name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ steps.info.outputs.push_image }}
          context: .
          file: ./Dockerfile
          tags: ${{ steps.info.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: |
            image.title=${{ matrix['description'] }}
            image.version=${{ steps.info.outputs.version }}
            image.created=${{ steps.info.outputs.created }}
            image.revision=${{ github.sha }}
